- README.md
- doc/changelog/0.103.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/files/_script/hugo-extended.sh
- src/files/_script/hugo-standard.sh
- src/project.yaml
Signed-off-by: Florin Lungu <info@lunguflorin.ro>
> hugo version 0.103.0

- README.md
- doc/changelog/0.107.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> release 0.107.0 of hugo

- README.md
- doc/changelog/0.109.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/docker/_base/_main.df
- src/docker/_base/image.df
- src/docker/alpine-ext/ext-alpine.df
- src/docker/debian-ext/Dockerfile
- src/docker/ubuntu-ext/Dockerfile
- src/files/_script/golang.sh
- src/files/_script/sass-embedded.sh
- src/project.yaml
Hugo version bump to v0.109.0 + dependencies upgrade
> hugo version bump and dependencies upgrade

- README.md
- doc/changelog/0.115.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- github_token.txt
- src/project.yaml
> Hugo version bump to 0.115.1

- README.md
- doc/changelog/0.115.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.115.2

- README.md
- doc/changelog/0.115.3.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.115.3

- README.md
- doc/changelog/0.115.4.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.115.4

- README.md
- doc/changelog/0.116.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.116.0

- README.md
- doc/changelog/0.116.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.116.1

- README.md
- doc/changelog/0.117.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.117.0

- README.md
- doc/changelog/0.118.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.118.2

- README.md
- doc/changelog/0.119.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.119.0

- README.md
- doc/changelog/0.120.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.120.1

- README.md
- doc/changelog/0.120.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.120.2

- README.md
- doc/changelog/0.120.3.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.120.3

- README.md
- doc/changelog/0.120.4.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.120.4

- README.md
- doc/changelog/0.121.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.121.0

- README.md
- doc/changelog/0.121.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.121.1

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/version_bump.yaml
- doc/template/README.md
This PR bumps GitHub workflow actions to their latest versions.
> Bump GitHub workflows to latest versions

- README.md
- doc/changelog/0.121.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.121.2

- README.md
- doc/changelog/0.122.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.122.0

- README.md
- doc/changelog/0.123.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.123.0

- README.md
- doc/changelog/0.123.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.123.1

- README.md
- doc/changelog/0.123.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.123.2

- README.md
- doc/changelog/0.123.3.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.123.3

- README.md
- doc/changelog/0.123.4.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.123.4

- README.md
- doc/changelog/0.123.6.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.123.6

- README.md
- doc/changelog/0.123.7.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.123.7

- README.md
- doc/changelog/0.123.8.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.123.8

- README.md
- doc/changelog/0.124.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.124.0

- README.md
- doc/changelog/0.125.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.125.0

- README.md
- doc/changelog/0.125.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.125.1

- README.md
- doc/changelog/0.125.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.125.2

- README.md
- doc/changelog/0.125.3.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.125.3

- README.md
- doc/changelog/0.125.4.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.125.4

- README.md
- doc/changelog/0.125.5.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.125.5

- README.md
- doc/changelog/0.125.6.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.125.6

- README.md
- doc/changelog/0.126.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.126.1

- README.md
- doc/changelog/0.126.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.126.2

- README.md
- doc/changelog/0.126.3.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.126.3

- README.md
- doc/changelog/0.127.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.127.0

- README.md
- doc/changelog/0.128.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.128.0

- README.md
- doc/changelog/0.128.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.128.1

- README.md
- doc/changelog/0.128.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.128.2

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sonarcloud.yml
- .github/workflows/version_bump.yaml
- src/files/_script/golang.sh
- src/files/_script/hugo-standard.sh
- src/files/_script/nodejs-glibc.sh
- src/files/_script/nodejs-musl.sh
- src/files/_script/pandoc.sh
Upgraded dependencies: 
- Go version > 1.22.5
- Node version > 22.4.0
- Pandoc version > 3.2.1
> upgraded various dependencies

- README.md
- doc/changelog/0.129.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.129.0

- README.md
- doc/changelog/0.130.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.130.0

- README.md
- doc/changelog/0.131.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.131.0

- README.md
- doc/changelog/0.132.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.132.0

- README.md
- doc/changelog/0.132.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.132.1

- README.md
- doc/changelog/0.132.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.132.2

- README.md
- doc/changelog/0.133.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.133.0

- README.md
- doc/changelog/0.133.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.133.1

- README.md
- doc/changelog/0.134.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.134.0

- README.md
- doc/changelog/0.134.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.134.1

- README.md
- doc/changelog/0.134.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.134.2

- README.md
- doc/changelog/0.134.3.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.134.3

- README.md
- doc/changelog/0.135.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.135.0

- README.md
- doc/changelog/0.136.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.136.0

- README.md
- doc/changelog/0.136.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.136.1

- README.md
- doc/changelog/0.136.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.136.2

- README.md
- doc/changelog/0.136.3.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.136.3

- README.md
- doc/changelog/0.136.4.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.136.4

- README.md
- doc/changelog/0.136.5.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.136.5

- README.md
- doc/changelog/0.137.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.137.0

- README.md
- doc/changelog/0.139.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.139.0

- README.md
- doc/changelog/0.139.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.139.2

- README.md
- doc/changelog/0.139.3.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.139.3

- README.md
- doc/changelog/0.139.4.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.139.4

- README.md
- doc/changelog/0.139.5.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.139.5

- README.md
- doc/changelog/0.140.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.140.1

- README.md
- doc/changelog/0.140.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.140.2

- README.md
- doc/changelog/0.141.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.141.0

- README.md
- doc/changelog/0.142.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.142.0

- README.md
- doc/changelog/0.143.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.143.0

- README.md
- doc/changelog/0.143.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.143.1

- README.md
- doc/changelog/0.144.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.144.0

- README.md
- doc/changelog/0.144.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.144.1

- README.md
- doc/changelog/0.145.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.145.0

- README.md
- doc/changelog/0.146.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.146.0

- README.md
- doc/changelog/0.146.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.146.2

- README.md
- doc/changelog/0.146.3.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.146.3

- README.md
- doc/changelog/0.146.5.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.146.5

- README.md
- doc/changelog/0.146.6.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.146.6

- README.md
- doc/changelog/0.147.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.147.0

- README.md
- doc/changelog/0.147.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.147.1

- README.md
- doc/changelog/0.147.2.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.147.2

- README.md
- doc/changelog/0.147.3.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.147.3

- README.md
- doc/changelog/0.147.4.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.147.4

- README.md
- doc/changelog/0.147.5.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.147.5

- README.md
- doc/changelog/0.147.9.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.147.9

- README.md
- doc/changelog/0.148.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.148.1

- README.md
- doc/changelog/0.149.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.149.0

- README.md
- doc/changelog/0.149.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.149.1

- README.md
- doc/changelog/0.150.1.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.150.1

- README.md
- doc/changelog/0.151.0.md
- doc/changelog/NEXT.md
- doc/tags.md
- src/project.yaml
> Hugo version bump to 0.151.0
